version: "3.8"

services:
  user_service:
    build: ./services/user_service
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./services/user_service:/app

  policy_service:
    build: ./services/policy_service
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./services/policy_service:/app

  claim_service:
    build: ./services/claim_service
    ports:
      - "5003:5003"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./services/claim_service:/app
